Add: stay 다중필터링
wecode-bootcamp-korea/31-2nd-DolHaru-backend pull request #10
Opened 2022-04-16 13:19 UTC by sangahnhan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 숙소 다중필터링

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 숙소 다중필터링 구현
2. 페이지네이션 구현
3. ORM 최적화 완료
4. 리펙토링 완료
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-04-18 01:54 UTC, jamessoun93 requested changes

2022-04-18 01:54 UTC, jamessoun93 commented on dolharu/urls.py
> +    path('staies', include('staies.urls'))
app명 수정해주세요.
```suggestion
    path('stays', include('stays.urls'))
```

2022-04-18 01:54 UTC, jamessoun93 commented on staies/urls.py
> +    path('/staylist' , StayListView.as_view())
복수형태로 만들어주면 리스트라는 뜻이겠죠?
```suggestion
    path('/stays' , StayListView.as_view())
```

2022-04-18 01:54 UTC, jamessoun93 commented on staies/views.py
> +    def query_optimized_staies(self,staies_paginated):
이 부분은 오후에 구두로 피드백 드리겠습니다.

2022-04-20 07:56 UTC, bigfanoftim approved these changes
LGTM 👍

2022-04-21 01:39 UTC, merged