[31기 김수훈] HostingView 작성
wecode-bootcamp-korea/31-2nd-DolHaru-backend pull request #14
Opened 2022-04-18 05:38 UTC by suhun96

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-18 08:19 UTC, bigfanoftim requested changes
`Stay` 인스턴스는 생성했는데 이미지 업로드 시 실패한다면 다시 롤백해야 하는 경우 아닌가요?
따라서 트랜잭션을 적용해야 합니다. `django db transaction` 공부하셔서 적용해보세요!

2022-04-18 08:19 UTC, bigfanoftim commented on staies/views.py
> +    )
```suggestion
    s3_client = boto3.client(
        's3',
        aws_access_key_id = settings.AWS_ACCESS_KEY_ID , 
        aws_secret_access_key = settings.AWS_SECRET_ACCESS_KEY
    )
```

2022-04-18 08:19 UTC, bigfanoftim commented on staies/views.py
> +            User.objects.get(id=user.id).update(is_host=True)
```suggestion
            user = request.user
            user.is_host=True
            user.save()
            
            images = request.FILES.getlist('image')
```

2022-04-18 08:19 UTC, bigfanoftim commented on staies/views.py
> +            [StayHighlight.objects.create(stay_id = new_stay.id, highlight_id =highlight_id) for highlight_id in request.POST.getlist('highlights')]
for문이 동작할때마다 create 하게 되면 db에 너무 많은 쿼리를 보내게 됩니다.
`bulk_create` 메소드 적용해주세요.

2022-04-19 05:26 UTC, suhun96 commented on staies/views.py
> +            [StayHighlight.objects.create(stay_id = new_stay.id, highlight_id =highlight_id) for highlight_id in request.POST.getlist('highlights')]
수정했습니다

2022-04-19 09:35 UTC, suhun96 commented on staies/tests.py
> +        self.assertEqual(response.status_code, 200)
<img width="1115" alt="스크린샷 2022-04-19 오후 6 19 00" src="https://user-images.githubusercontent.com/97911154/163972267-68fe04d4-8aa9-48dc-91f0-fc838f027184.png">

호준님 테스트에 자꾸 이문제가 발생합니다

2022-04-21 06:40 UTC, bigfanoftim requested changes

2022-04-21 06:40 UTC, bigfanoftim commented on stays/views.py
> +        )
들여쓰기 맞춰서 작성해주세요.

2022-04-21 06:40 UTC, bigfanoftim commented on stays/views.py
> +                    StayImage.objects.create(image_url = image_url, stay_id = new_stay.id)
맨 아래로 이동

2022-04-21 07:26 UTC, bigfanoftim approved these changes

2022-04-21 07:27 UTC, merged