[31기 김수훈] HostingView 작성
wecode-bootcamp-korea/31-2nd-DolHaru-backend pull request #16
Opened 2022-04-20 06:42 UTC by suhun96

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-20 07:57 UTC, bigfanoftim requested changes

2022-04-20 07:57 UTC, bigfanoftim commented on staies/views.py
> +            )
transaction 👀

2022-04-21 01:58 UTC, bigfanoftim requested changes

2022-04-21 01:58 UTC, bigfanoftim commented on staies/views.py
> +                if len(images) <= 2:
`2보다 같거나 작으면` 이라는 조건인데, 에러 메세지랑 말이 좀 안맞네요.

2022-04-21 01:58 UTC, bigfanoftim commented on staies/views.py
> +        )
들여쓰기 맞춰서 작성해주세요. 코드 push 전 다시 한 번 확인하세요.

2022-04-21 01:58 UTC, bigfanoftim commented on staies/views.py
> +                    longitude       = data.get('longitude', True)
`get` 메소드에 2번째 인자로 모두 True를 넣어주고 있는데 그런 이유가 있나요? 
동작 원리를 제대로 파악하고 계신건지 의문이 듭니다.

2022-04-21 01:58 UTC, bigfanoftim commented on staies/views.py
> +            return JsonResponse({'message' : 'KEY_ERROR'} , status = 402)
402는 어떤 에러인가요?

2022-04-21 05:03 UTC, suhun96 commented
컨플릭트 해결했습니다.

2022-04-21 05:14 UTC, bigfanoftim commented
컨플릭트를 해결하신게 아니라 코드를 다 지우신 것 같습니다 수훈님
매번 말씀드리지만 본인 PR의 `Files changed`를 꼭 확인해주세요. 만약 지금 브랜치가 아니라 다른 브랜치로 새로 올리실 생각이었다면 이건 close 해주세요.

2022-04-21 05:16 UTC, closed without merging