Add: Kakao Login
wecode-bootcamp-korea/31-2nd-DolHaru-backend pull request #7
Opened 2022-04-15 07:54 UTC by sangahnhan

Add: Kakao Login

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 인가코드를 받아서 토큰 발급

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 인가 코드를 받고 카카오 토큰 받기
- 카카오 토큰 받고 유저데이터 받기
- 유저데이터로 유저데이터가 없을시 유저생성
- 토큰생성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-04-18 01:36 UTC, jamessoun93 requested changes

2022-04-18 01:36 UTC, jamessoun93 commented on users/models.py
> +    kakao_id   = models.CharField(max_length=20)
모델 수정사항 반영해서 여기도 수정해주세요!

2022-04-18 01:36 UTC, jamessoun93 commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
- TestCase의 단위가 카카오 인증을 통한 새로운 유저를 생성하는 로직만 테스트하는 단위가 되어서는 안됩니다. 이렇게 만드실거라면 그냥 함수하나만 있으면 되겠죠?
- TestCase는 유저관련 테스트를 전부 그룹핑해주는 클래스의 형태로 만들어주시고, 그 안에 여러가지 성공/실패를 테스트하는 단위 테스트 함수들을 포함시켜주세요.

2022-04-18 01:36 UTC, jamessoun93 commented on users/views.py
> +        return user
카카오에 잘못된 토큰으로 유저정보를 요청할 시에 대한 에러처리가 되어있지 않네요. 추가해주세요.

2022-04-18 03:12 UTC, sangahnhan commented on users/views.py
> +        return user
잘못된 토큰으로 유저정보를 요청할 시 user_data['id'] 이 부분에서 KeyError 를 뱉어서 따로 처리하지 않았습니다. 혹시 따로 에러처리를 해야하는 건가요?

2022-04-18 04:21 UTC, sangahnhan commented on users/models.py
> +    kakao_id   = models.CharField(max_length=20)
넵 반영했습니다

2022-04-18 04:22 UTC, sangahnhan commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
request_access_token : access_token 없을 경우
request_user_data : 유저데이터가 없을 경우
request_access_token, request_user_data : 다 잘될경우, 유저정보, 토큰정보 맞는지
위 3가지 테스트코드를 작성헀습니다. 추가로 테스트해야할 부분이 있을까요?

2022-04-18 07:35 UTC, bigfanoftim requested changes
모킹 클래스 관련 리뷰 확인하시고 전부 적용해주세요!!

2022-04-18 07:35 UTC, bigfanoftim commented on users/tests.py
> +        mocked_token.return_value = MockedToken().json()
상안님 메소드를 통째로 모킹하는 경우엔 굳이 Mocking 클래스를 만드실 필요가 없습니다. 어차피 반환되는 값만 정해주면 되기 때문이죠. 저희가 Mocking 클래스를 만들었던 이유는 해당 메소드 전부가 아닌 하나의 request 요청의 값만 모킹하기 위함입니다. 그래서 내부에 `json()` 메소드를 만들어 주어서 그 값이 일치하게 만들어준것이구요
```suggestion
        mocked_token.return_value = {"message" : "no_access_token"}
```

2022-04-18 07:35 UTC, bigfanoftim commented on users/views.py
> +        return user
사실 KeyError를 핸들링하는 것과는 별개로 잘못된 토큰으로 유저를 요청할때에 status code를 기준으로 핸들링 해주면 좋을 것 같아요!!

정말 너무나 많은 이유로 키에러를 유발할 수 있기 때문에 그렇습니다!!

2022-04-20 07:54 UTC, bigfanoftim approved these changes
LGTM 👍

2022-04-20 07:55 UTC, merged